### ISSUE TITLE
 APT source whitelist request for ppa:hvr/ghc

### ISSUE THREAD

**Issue by bgamari** [travis-ci/apt-source-whitelist#103]
`ppa:hvr/ghc`serves the majority of Haskell Travis users, containing several versions of the GHC compiler.

**Comment by bgamari** [comment]
Bah, this is already whitelisted. Sorry for the noise.

**Comment by danse** [comment]
:+1: this is whitelisted in this repo, but i still get errors in Travis builds

**Comment by danse** [comment]
My bad, i was using the wrong alias, the source works
