### ISSUE TITLE
APT source whitelist request for cassou/emacs

### ISSUE THREAD

**Issue by gracjan** [travis-ci/apt-source-whitelist#164]
ppa:cassou/emacs

**Comment by tripleee** [comment]
Seriously?  The [PPA description](https://launchpad.net/~cassou/+archive/ubuntu/emacs) says [DEPRECATED] in ugly capital letters.

You should probably be looking at https://launchpad.net/~ubuntu-elisp/+archive/ppa which was done in [#367](https://github.com/travis-ci/apt-package-whitelist/issues/367).

**Comment by gracjan** [comment]
We need this for Emacs23 compatibility testing.

**Comment by lunaryorn** [comment]
@gracjan Emacs 23?  cassou/emacs doesn't even include that version…

**Comment by gracjan** [comment]
@lunaryorn, you are right. cassou/emacs is used for Emacs24 as Emacs23 is present by default.

I basically need this set: https://github.com/haskell/haskell-mode/blob/master/.travis.yml#L17-L36

**Comment by gracjan** [comment]
@tripleee: #367 does not look 'done'. Why do you say it is done?

**Comment by tripleee** [comment]
@gracjan My bad, I probably looked at the wrong tab in my browser.

**Comment by tripleee** [comment]
I was also confused by the fact that `emacs24` is the default Emacs most places now.  You might eventually need to worry about where to obtain `emacs23` eventually, but for now, Travis is using an old Ubuntu version which does not include `emacs24` by default.  (`emacs23` it is included in Ubuntu up through `trusty` aka Ubuntu 14.04. Travis runs 12.04 for the time being.)  Using the `cassou` PPA for `emacs24` seems to be the standard workaround. Perhaps this should be reopened?
