### ISSUE TITLE
APT source whitelist request for mono-project

### ISSUE THREAD

**Issue by thesupremecommander** [travis-ci/apt-source-whitelist#170]
The versions of Mono available in the official repos are severely outdated, and it would be helpful to be able to install those without setting our build environment to C#.

The [official Mono project page](http://www.mono-project.com/docs/getting-started/install/linux/) lists the required repos.

**Comment by shepmaster** [comment]
This would be great, especially as the Mono / C# build environment is [already using these](https://github.com/travis-ci/travis-build/blob/8382790533fc233c0b1921504af4bf7c9d75795b/lib/travis/build/script/csharp.rb#L36-L47), so hopefully they should be trustworthy.
