### ISSUE TITLE
APT source whitelist request for llvm-toolchain-trusty

### ISSUE THREAD

**Issue by poletti-marco** [travis-ci/apt-source-whitelist#199]
I'd like the following to be added:

    deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main
    deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty main
    # 3.6 
    deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main
    deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main
    # 3.7 
    deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main
    deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main

These are just Trusty-specific variants of the Precise repos, that are already whitelisted.
See http://llvm.org/apt/

**Comment by h-2** [comment]
:+1: :+1: :+1:

Please merge!

**Comment by dsvensson** [comment]
Is there any technical reason why this is still not merged?

**Comment by poletti-marco** [comment]
Not AFAIK.

**Comment by wesm** [comment]
+1

**Comment by wesm** [comment]
I would also like to see LLVM 3.8 made available on Trusty. Please advise

**Comment by poletti-marco** [comment]
This is probably not going to happen.
See the discussion at the end of https://github.com/travis-ci/apt-source-whitelist/pull/205.
