### ISSUE TITLE
APT source whitelist request for llvm-toolchain-precise-3.8

### ISSUE THREAD

**Issue by d-frey** [travis-ci/apt-source-whitelist#254]
Now that LLVM/Clang 3.8 has been released, please add:

deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.8 main
deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.8 main

(also for trusty, etc. if you like)

**Comment by springmeyer** [comment]
Also just hit this. Would be great to have soon.

**Comment by justinmk** [comment]
The LLVM apt repo http://llvm.org/apt was taken down until further notice. see http://stackoverflow.com/questions/37558151/travis-ci-build-failing/37559463#37559463
