### ISSUE TITLE
APT source whitelist request for llvm-toolchain-trusty

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/apt-source-whitelist#332]
to mirror precise (ref: http://apt.llvm.org/)

llvm-toolchain-trusty:

deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main

llvm-toolchain-trusty-3.8:

deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main

llvm-toolchain-trusty-3.9:

deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main

key: http://apt.llvm.org/llvm-snapshot.gpg.key

**Comment by BanzaiMan** [comment]
It should now be possible to use LLVM 3.9 and 4.0 on Trusty.

**Comment by grooverdan** [comment]
confirmed. looks good. Thanks.
