### ISSUE TITLE
APT source whitelist request for ppa:ubuntugis/ppa

### ISSUE THREAD

**Issue by carlodef** [travis-ci/apt-source-whitelist#358]
deb http://ppa.launchpad.net/ubuntugis/ppa/ubuntu trusty main
    deb-src http://ppa.launchpad.net/ubuntugis/ppa/ubuntu trusty main
https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa

**Comment by nuest** [comment]
Duplicate of #26 ?

**Comment by carlodef** [comment]
Yes indeed, you're right.
