### ISSUE TITLE
Whitelisted source is disallowed

### ISSUE THREAD

**Issue by lgrahl** [travis-ci/apt-source-whitelist#369]
I'm having trouble using a whitelisted source. Check out [this build](https://travis-ci.org/rawrtc/rawrtc/jobs/215676184). I've added the `george-edison55-precise-backport` PPA which is whitelisted... but this is the output:
> Disallowing sources: george-edison55-precise-backport
To add unlisted APT sources, follow instructions in https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon

The [config](https://travis-ci.org/rawrtc/rawrtc/jobs/215676184/config) ([original config](https://github.com/rawrtc/rawrtc/blob/9ad2731ab1c0e836e400837a1e2a9104c7367ea6/.travis.yml)) looks perfectly fine to me - it should work according to the chapter the error output above mentions. What am I doing wrong?

**Comment by dracos** [comment]
The name is "george-edison55-precise-backports", not "george-edison55-precise-backport".

**Comment by lgrahl** [comment]
Oh, thanks! I haven't seen that.
