### ISSUE TITLE
APT source whitelist request for llvm-toolchain-trusty-5.0

### ISSUE THREAD

**Issue by Morwenn** [travis-ci/apt-source-whitelist#372]
deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main
deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main

deb http://apt.llvm.org/precise/ llvm-toolchain-precise-5.0 main
deb-src http://apt.llvm.org/precise/ llvm-toolchain-precise-5.0 main

**Comment by grooverdan** [comment]
The following works with sudo: false

<pre>
addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-5.0
      - llvm-5.0-dev
</pre>

And build with CC/CXX=clang{,++}-5.0

**Comment by Morwenn** [comment]
@grooverdan It works well (even without llvm-5.0-dev that I apparently don't need), thanks!

**Comment by BanzaiMan** [comment]
Does the precise source exist? Does not show it. http://apt.llvm.org/

**Comment by BanzaiMan** [comment]
Anyhow, I added the Trusty source with https://github.com/travis-ci/apt-source-whitelist/commit/2b5b082b09878010bd06e5293750fa79002d2b5c.

**Comment by grooverdan** [comment]
Looks like a precise source doesn't exist looking at their builder: http://llvm-jenkins.debian.net/view/5.0/

**Comment by Morwenn** [comment]
Uh, I probably blindly copy-pasted a previous request after having checked that the Trusty source existed. Sorry.
