### ISSUE TITLE
APT source whitelist request for ppa:boost-latest/ppa

### ISSUE THREAD

**Issue by LavenderMoon** [travis-ci/apt-source-whitelist#89]
deb http://ppa.launchpad.net/boost-latest/ppa/ubuntu precise main
    deb-src http://ppa.launchpad.net/boost-latest/ppa/ubuntu precise main

**Comment by maqifrnswa** [comment]
I think it's already added:
https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json#L8

**Comment by LavenderMoon** [comment]
Oh, you're right. It gave me errors on boost-latest-ppa, but boost-latest should work.
