### ISSUE TITLE
APT source whitelist request for ppa:texlive-backports/ppa

### ISSUE THREAD

**Issue by Alghamdi** [travis-ci/apt-source-whitelist#99]
[This](https://launchpad.net/~texlive-backports/+archive/ubuntu/ppa) is a backports of the latest TeX Live from Ubuntu 12.10 to Ubuntu 12.04 LTS by Ubuntu's TeX Live maintainer, Jeremy Bicha,

**Comment by cscott** [comment]
Dup of #55.

**Comment by Alghamdi** [comment]
Sorry,.. :+1:
